# Generated by Django 3.1.6 on 2022-04-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_likes_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
